### ISSUE TITLE
called `Result::unwrap()` on an `Err` value: ()

### ISSUE THREAD

**Issue by krugman420** [Technosorcery/sd2snes-lttp-rando-tracker#27]
Hi, first off thank you for this wonderful tool! I'm using the 1.0.0 Windows binary, and it sometimes seems to get stuck (ie. not updating, and requiring a restart) after displaying the message in the title. Please let me know how I can help you figure out the problem. On my SD2SNES I have the newest 1.8.0 firmware and usb2snes v8 (from https://github.com/RedGuyyyy/usb2snesw ). Thanks!

**Comment by jhelwig** [comment]
Fortunately, there's only one place where `unwrap()` is being called: https://github.com/jhelwig/sd2snes-lttp-rando-tracker/blob/a5919f089182a6ffc4644a57d18beebc1fc1da2a/src/main.rs#L208

I'm guessing that the [mutex was poisoned](https://doc.rust-lang.org/std/sync/struct.Mutex.html#poisoning) because of a panic elsewhere, which is why the `unwrap()` is panicing there. Is there any other output that you're seeing before the `unwrap() on Err`? You might need to run the tracker with `-vv` so the `lazy_panic` formatter gives more useful information. https://github.com/jhelwig/sd2snes-lttp-rando-tracker/blob/a5919f089182a6ffc4644a57d18beebc1fc1da2a/src/main.rs#L596-L602

**Comment by krugman420** [comment]
Thanks for pointing me to -vv. Here's a screenshot of the output I got yesterday. Hope it helps!

![tracker-error](https://user-images.githubusercontent.com/14757999/46797338-90ccf480-cd57-11e8-9636-2adb2eba3afd.png)

**Comment by jhelwig** [comment]
I forgot that the binaries I put up in the releases don't have the debugging symbols. :( Any chance you could try building/running from source? If not, don't worry about it, I can build a development version of the binary for Windows and put it up somewhere so you can grab it.

**Comment by krugman420** [comment]
Unfortunately I'm unfamiliar with the process on Windows. I can run the development version binary once it's up, and get back to you ASAP.

**Comment by jhelwig** [comment]
This is built from the tip of the master branch, instead of the 1.0.0 tag: [sd2snes-lttp-rando-tracker.zip](https://github.com/jhelwig/sd2snes-lttp-rando-tracker/files/2475751/sd2snes-lttp-rando-tracker.zip)

**Comment by krugman420** [comment]
Here's the output I got when using the new build:

![tracker-error2](https://user-images.githubusercontent.com/14757999/46917198-cc242900-cfcc-11e8-8733-bffe80af5096.png)

**Comment by jhelwig** [comment]
Hm. :\ I'm going to have to try updating my SD2SNES to see if it happens for me so I can do some more interactive debugging. Have you noticed any pattern to when the panic happens?

**Comment by krugman420** [comment]
Yeah, after playing a bunch of seeds in the last few days, a clear pattern has emerged. Panics start at the very beginning. I usually upload a seed rom via usb2snes FileViewer --> close usb2snes --> load game --> load tracker --> panic occurs more often than not --> few tracker restarts sometimes make it stabilize, sometimes not. Sometimes panic occurs an hour into the game. Whether I start the tracker early, or later into the game, doesn't seem to make a difference.

Let me know if you need more info or any kind of help. Your app has quickly become an essential tool for my stream :) Good luck!

**Comment by jhelwig** [comment]
I haven't been able to reproduce the panic yet using either a v29, or v30 randomizer ROM with the 1.8.0 usb2snes firmware.

**Comment by jhelwig** [comment]
Ok. I was finally able to update it. When I was trying to reproduce it I wasn't using the usb2snes windows app to upload the ROM & then boot into it.

This might actually be a bug in usb2snes. If I both upload & use the Windows software to boot into a ROM, I see the panic, but if I use the app to upload the ROM, reset the SNES, then use the app to boot into the ROM, I don't see the panic.

I haven't dug in enough yet to say for certain whether it's a bug in usb2snes, but at least now I think we've got a work around.

**Comment by krugman420** [comment]
Sorry, you caught me at a bad time with the permalink request. I just deleted all of them and haven't had time to start new ones. The problem however has shown itself at the start of basically every one.

Regarding usb2snes, I didn't even know it can be used to start up a ROM. I never do that myself, and always go the upload-->soft reset SNES route. Maybe a hard reset gives different results? I will update this reply when I have tested it out. The problem for me is really ubiquitous though. Would it be helpful if I uploaded the contents of my sd2snes folder? I might need to try the 1.7 firmware to see if the cause is somewhere else in my setup.

**Comment by jhelwig** [comment]
Yeah, as far as I can tell, there's some weird state that the SD2SNES can get into after uploading a ROM, but it seems like there's a few ways to potentially clear it. If I go and delete another file, it seems like it clears the bugged state. Hitting the reset button on the SNES itself also seems to clear it.

**Comment by jhelwig** [comment]
@krugman420 Do you still get this behavior with the new 1.9.0 sd2snes firmware? From a quick check, I wasn't able to reproduce it, but I didn't spend a lot of time trying.
