### ISSUE TITLE
Show location tool tips on hover

### ISSUE THREAD

**Issue by jhelwig** [Technosorcery/sd2snes-lttp-rando-tracker#425]
https://lttp-tracker.firebaseapp.com/ shows the location name, and a handy reminder about what item is required to access the location when you hover the mouse over it. We should do that, too.

**Comment by jhelwig** [comment]
The firebase version does this as part of the highlight/unhighlight for locations & dungeons.

https://github.com/stochaztic/lttp-tracker/blob/67050baca17d2bdec78ac278eaa2cb1ad3025aeb/public/script/main.js#L166-L186
```javascript
// Highlights a chest location and shows the name as caption
function highlight(x){
    document.getElementById(x).style.backgroundImage = "url(/images/highlighted.png)";
    document.getElementById("caption").innerHTML = chests[x].name;
}

function unhighlight(x){
    document.getElementById(x).style.backgroundImage = "url(/images/poi.png)";
    document.getElementById("caption").innerHTML = "&nbsp;";
}

// Highlights a chest location and shows the name as caption (but for dungeons)
function highlightDungeon(x){
    document.getElementById("dungeon"+x).style.backgroundImage = "url(/images/highlighted.png)";
    document.getElementById("caption").innerHTML = dungeons[x].name;
}

function unhighlightDungeon(x){
    document.getElementById("dungeon"+x).style.backgroundImage = "url(/images/poi.png)";
    document.getElementById("caption").innerHTML = "&nbsp;";
}
```

This doesn't really seem like a Vue-like way of doing it, though. The highlighting/unhighlighting feels like it should be applying/removing a class, instead of editing properties directly. Also, setting the caption seems like it should be modifying some data that a caption component could be looking at.

**Comment by jhelwig** [comment]
We'll want to pull in the names from lttp-tracker's [script/chests.js](https://github.com/stochaztic/lttp-tracker/blob/c9384fa80dc9df34588fe414582156e699efc877/public/script/chests.js#L2272) into logic/poi_locations.yaml as the `hoverText`.

Eg:
```javascript
    name: "King's Tomb <img src='/images/boots.png' class='mini'> + <img src='/images/glove2.png' class='mini'>/<img src='/images/mirror.png' class='mini'>",
```

https://github.com/Technosorcery/sd2snes-lttp-rando-tracker/blob/4373b9b571b2df8e3d37b2006cbb48b69d7fdf07/logic/poi_locations.yaml#L2-L3

**Comment by jhelwig** [comment]
#432 got most of this. Still need to update all the hoverText in the YAML files at some point.

**Comment by jtappa** [comment]
is this "done" now? should we close the issue?

**Comment by jhelwig** [comment]
Yup! It's done.
