### ISSUE TITLE
Highlight location/dungeon on hover

### ISSUE THREAD

**Issue by jhelwig** [Technosorcery/sd2snes-lttp-rando-tracker#430]
This is pretty straightforward for the locations, but is a bit more involved for the dungeons. Because the dungeons are nested spans, we'll probably need to do something in JavaScript to make sure that the dungeon is highlighted regardless of whether the cursor is over the "dungeon" or the "boss".

**Comment by jhelwig** [comment]
https://michaelnthiessen.com/hover-in-vue/ appears to have some good ideas on how to handle this. A combination of toggling a data member of the component, and using that to toggle whether the "hover" class is active that changes the background image.

**Comment by jhelwig** [comment]
https://michaelnthiessen.com/dynamically-add-class-name/ also appears to be a handy resource.

**Comment by jtappa** [comment]
Will be resolved by https://github.com/Technosorcery/sd2snes-lttp-rando-tracker/pull/494
